MODULE_ID='kubernetes'
MODULE_NAME='Kubernetes'
MODULE_DESCRIPTION='Interactive Kubernetes helpers'
MODULE_COMMANDS=(kgp kexec)
MODULE_ALLOW_COMMAND_SHADOWS=()
MODULE_DEPENDENCIES=(kubectl)
MODULE_PLATFORMS=(linux wsl)
