# Shared installer and management functions.
emulate -L zsh
setopt EXTENDED_GLOB

typeset -gr ZT_ROOT="${ZSH_TOOLS_ROOT:-${${(%):-%N}:A:h:h}}"
typeset -gr ZT_CONFIG_DIR="${ZSH_TOOLS_CONFIG_HOME:-${XDG_CONFIG_HOME:-$HOME/.config}/zsh-tools}"
typeset -gr ZT_STATE_DIR="${ZSH_TOOLS_STATE_HOME:-${XDG_STATE_HOME:-$HOME/.local/state}/zsh-tools}"
typeset -gr ZT_BIN_DIR="${ZSH_TOOLS_BIN_HOME:-$HOME/.local/bin}"
typeset -gr ZT_ZSHRC="${ZSH_TOOLS_ZSHRC:-${ZDOTDIR:-$HOME}/.zshrc}"
typeset -gr ZT_MARKER_START='# >>> zsh-tools >>>'
typeset -gr ZT_MARKER_END='# <<< zsh-tools <<<'
typeset -gr ZT_OWNER_FILE="$ZT_CONFIG_DIR/.managed-by-zsh-tools"

typeset -ga ZT_MODULES
typeset -gA ZT_MODULE_NAME ZT_MODULE_DESCRIPTION ZT_MODULE_COMMANDS
typeset -gA ZT_MODULE_DEPENDENCIES ZT_MODULE_PLATFORMS ZT_MODULE_ALLOW_COMMAND_SHADOWS

zt_info() { print -- "• $1"; }
zt_ok() { print -- "✓ $1"; }
zt_warn() { print -- "⚠ $1"; }
zt_error() { print -u2 -- "✗ $1"; }

zt_is_wsl() {
  [[ -r /proc/sys/kernel/osrelease ]] &&
    grep -qi microsoft /proc/sys/kernel/osrelease
}

zt_platform() {
  if zt_is_wsl; then print wsl; else print linux; fi
}

zt_registry_load() {
  ZT_MODULES=()
  ZT_MODULE_NAME=()
  ZT_MODULE_DESCRIPTION=()
  ZT_MODULE_COMMANDS=()
  ZT_MODULE_DEPENDENCIES=()
  ZT_MODULE_PLATFORMS=()
  ZT_MODULE_ALLOW_COMMAND_SHADOWS=()

  local metadata
  for metadata in "$ZT_ROOT"/modules/[a-z-]##/module.zsh(N); do
    local MODULE_ID='' MODULE_NAME='' MODULE_DESCRIPTION=''
    local -a MODULE_COMMANDS=() MODULE_DEPENDENCIES=() MODULE_PLATFORMS=()
    local -a MODULE_ALLOW_COMMAND_SHADOWS=()
    source "$metadata"
    if [[ -z "$MODULE_ID" || ! -r "${metadata:h}/tools.zsh" ]]; then
      zt_error "Invalid module metadata: $metadata"
      return 1
    fi
    ZT_MODULES+=("$MODULE_ID")
    ZT_MODULE_NAME[$MODULE_ID]="$MODULE_NAME"
    ZT_MODULE_DESCRIPTION[$MODULE_ID]="$MODULE_DESCRIPTION"
    ZT_MODULE_COMMANDS[$MODULE_ID]="${(j: :)MODULE_COMMANDS}"
    ZT_MODULE_DEPENDENCIES[$MODULE_ID]="${(j: :)MODULE_DEPENDENCIES}"
    ZT_MODULE_PLATFORMS[$MODULE_ID]="${(j: :)MODULE_PLATFORMS}"
    ZT_MODULE_ALLOW_COMMAND_SHADOWS[$MODULE_ID]="${(j: :)MODULE_ALLOW_COMMAND_SHADOWS}"
  done
}

zt_module_exists() {
  (( ${ZT_MODULES[(Ie)$1]} ))
}

zt_module_supported() {
  local id="$1" current
  current="$(zt_platform)"
  local -a platforms=(${=ZT_MODULE_PLATFORMS[$id]})
  (( ${platforms[(Ie)$current]} ))
}

zt_module_missing_dependencies() {
  local id="$1" dependency
  local -a missing=()
  for dependency in ${=ZT_MODULE_DEPENDENCIES[$id]}; do
    command -v "$dependency" >/dev/null 2>&1 || missing+=("$dependency")
  done
  print -r -- "${(j: :)missing}"
}

zt_command_conflicts() {
  local id="$1" command_name existing
  local -a conflicts=()
  local -a allowed_shadows=(${=ZT_MODULE_ALLOW_COMMAND_SHADOWS[$id]})
  for command_name in ${=ZT_MODULE_COMMANDS[$id]}; do
    existing="$(whence -w "$command_name" 2>/dev/null || true)"
    [[ -z "$existing" ]] && continue
    if [[ "$existing" == "$command_name: command" ]] &&
      (( ${allowed_shadows[(Ie)$command_name]} )); then
      continue
    fi
    conflicts+=("$command_name")
  done
  print -r -- "${(j: :)conflicts}"
}

zt_validate_markers() {
  [[ -r "$ZT_ZSHRC" ]] || return 0
  local starts ends
  starts="$(grep -Fxc -- "$ZT_MARKER_START" "$ZT_ZSHRC" 2>/dev/null || true)"
  ends="$(grep -Fxc -- "$ZT_MARKER_END" "$ZT_ZSHRC" 2>/dev/null || true)"
  [[ "$starts" == "$ends" && "$starts" -le 1 ]]
}

zt_validate_paths() {
  if [[ -e "$ZT_CONFIG_DIR" || -L "$ZT_CONFIG_DIR" ]]; then
    [[ -d "$ZT_CONFIG_DIR" && -r "$ZT_OWNER_FILE" ]] || {
      zt_error "$ZT_CONFIG_DIR exists but is not managed by zsh-tools."
      return 1
    }
  fi

  local command_link="$ZT_BIN_DIR/zsh-tools"
  if [[ -e "$command_link" || -L "$command_link" ]]; then
    [[ -L "$command_link" && "${command_link:A}" == "${ZT_ROOT}/bin/zsh-tools" ]] || {
      zt_error "$command_link already exists and is not managed by this repository."
      return 1
    }
  fi

  zt_validate_markers || {
    zt_error "Managed markers in $ZT_ZSHRC are inconsistent."
    return 1
  }
}

zt_timestamp() {
  date '+%Y%m%dT%H%M%S'
}

zt_backup_zshrc() {
  [[ -e "$ZT_ZSHRC" ]] || return 0
  mkdir -p -- "$ZT_STATE_DIR/backups"
  local backup="$ZT_STATE_DIR/backups/zshrc-$(zt_timestamp)"
  command cp -p -- "$ZT_ZSHRC" "$backup"
  print -r -- "$backup"
}

zt_write_enabled_modules() {
  local -a modules=("$@")
  mkdir -p -- "$ZT_CONFIG_DIR"
  {
    print '# Generated by zsh-tools. Edit through the zsh-tools command.'
    print -n 'enabled_modules=('
    local id
    for id in "${modules[@]}"; do printf ' %q' "$id"; done
    print ' )'
  } > "$ZT_CONFIG_DIR/enabled-modules.zsh"
}

zt_write_init() {
  local quoted_root="${(q)ZT_ROOT}"
  local quoted_config="${(q)ZT_CONFIG_DIR}"
  {
    print '# Generated by zsh-tools. Do not edit manually.'
    print "typeset -gr ZSH_TOOLS_ROOT=$quoted_root"
    print "source $quoted_config/enabled-modules.zsh"
    print 'for zsh_tools_module in "${enabled_modules[@]}"; do'
    print '  zsh_tools_file="$ZSH_TOOLS_ROOT/modules/$zsh_tools_module/tools.zsh"'
    print '  [[ -r "$zsh_tools_file" ]] && source "$zsh_tools_file"'
    print 'done'
    print 'unset zsh_tools_module zsh_tools_file'
  } > "$ZT_CONFIG_DIR/init.zsh"
}

zt_write_state() {
  local backup="$1" allow_conflicts="$2"
  shift 2
  local -a modules=("$@")
  mkdir -p -- "$ZT_STATE_DIR"
  {
    print '# Generated by zsh-tools.'
    printf 'repository_path=%q\n' "$ZT_ROOT"
    printf 'installed_at=%q\n' "$(date -Iseconds)"
    printf 'zshrc_path=%q\n' "$ZT_ZSHRC"
    printf 'zshrc_backup=%q\n' "$backup"
    printf 'allow_conflicts=%q\n' "$allow_conflicts"
    print -n 'installed_modules=('
    local id
    for id in "${modules[@]}"; do printf ' %q' "$id"; done
    print ' )'
  } > "$ZT_STATE_DIR/install-state.zsh"
}

zt_install_zshrc_block() {
  [[ -e "$ZT_ZSHRC" ]] || : > "$ZT_ZSHRC"
  grep -Fqx -- "$ZT_MARKER_START" "$ZT_ZSHRC" && return 0
  {
    print
    print -r -- "$ZT_MARKER_START"
    print -r -- '[[ -r "${XDG_CONFIG_HOME:-$HOME/.config}/zsh-tools/init.zsh" ]] && source "${XDG_CONFIG_HOME:-$HOME/.config}/zsh-tools/init.zsh"'
    print -r -- "$ZT_MARKER_END"
  } >> "$ZT_ZSHRC"
}

zt_validate_loaded_commands() {
  local id command_name failed=0
  local init_file="$ZT_CONFIG_DIR/init.zsh"
  for id in "$@"; do
    for command_name in ${=ZT_MODULE_COMMANDS[$id]}; do
      if ZDOTDIR=/nonexistent zsh -dfc "source ${(q)init_file}; whence -w ${(q)command_name}" >/dev/null 2>&1; then
        :
      else
        zt_error "$command_name failed to load."
        failed=1
      fi
    done
  done
  return "$failed"
}

zt_print_summary() {
  local -a modules=("$@")
  local id missing command_name
  local ready=0 partial=0 commands=0

  print
  print 'Installation summary'
  print
  for id in "${modules[@]}"; do
    missing="$(zt_module_missing_dependencies "$id")"
    if [[ -n "$missing" ]]; then
      zt_warn "${ZT_MODULE_NAME[$id]}: installed, missing dependencies: $missing"
      ((partial++))
    else
      zt_ok "${ZT_MODULE_NAME[$id]}: ready"
      ((ready++))
    fi
    for command_name in ${=ZT_MODULE_COMMANDS[$id]}; do
      print "  ✓ $command_name"
      ((commands++))
    done
  done
  print
  print "Modules: $ready ready / $partial partial"
  print "Commands: $commands installed"
}

zt_install() {
  local allow_conflicts="$1"
  shift
  local -a modules=("$@")
  local id conflicts backup=''

  zt_validate_paths || return 1

  for id in "${modules[@]}"; do
    zt_module_exists "$id" || { zt_error "Unknown module: $id"; return 2; }
    zt_module_supported "$id" || {
      zt_error "Module '$id' does not support platform '$(zt_platform)'."
      return 2
    }
    conflicts="$(zt_command_conflicts "$id")"
    if [[ -n "$conflicts" && "$allow_conflicts" != true ]]; then
      zt_error "Module '$id' conflicts with existing commands: $conflicts"
      zt_info 'Re-run with --allow-conflicts only after reviewing the existing definitions.'
      return 3
    fi
  done

  backup="$(zt_backup_zshrc)"
  mkdir -p -- "$ZT_CONFIG_DIR" "$ZT_BIN_DIR"
  print 'zsh-tools' > "$ZT_OWNER_FILE"
  zt_write_enabled_modules "${modules[@]}"
  zt_write_init
  ln -s -- "$ZT_ROOT/bin/zsh-tools" "$ZT_BIN_DIR/zsh-tools" 2>/dev/null || true
  zt_install_zshrc_block
  zt_write_state "$backup" "$allow_conflicts" "${modules[@]}"

  if ! zt_validate_loaded_commands "${modules[@]}"; then
    zt_error 'Installation validation failed. Run zsh-tools doctor for details.'
    return 1
  fi

  zt_print_summary "${modules[@]}"
  print
  zt_info 'Restart Zsh with: exec zsh'
}

zt_read_enabled_modules() {
  typeset -ga enabled_modules=()
  [[ -r "$ZT_CONFIG_DIR/enabled-modules.zsh" ]] &&
    source "$ZT_CONFIG_DIR/enabled-modules.zsh"
}

zt_remove_zshrc_block() {
  [[ -r "$ZT_ZSHRC" ]] || return 0
  local temporary="${ZT_ZSHRC}.zsh-tools.$$"
  awk -v start="$ZT_MARKER_START" -v end="$ZT_MARKER_END" '
    $0 == start { managed = 1; next }
    $0 == end { managed = 0; next }
    !managed { print }
  ' "$ZT_ZSHRC" > "$temporary"
  command mv -- "$temporary" "$ZT_ZSHRC"
}

zt_uninstall() {
  zt_validate_markers || {
    zt_error "Managed markers in $ZT_ZSHRC are inconsistent; no files were changed."
    return 1
  }
  [[ -r "$ZT_OWNER_FILE" ]] || {
    zt_error 'No managed zsh-tools installation was found.'
    return 1
  }

  local backup=''
  backup="$(zt_backup_zshrc)"
  zt_remove_zshrc_block

  local command_link="$ZT_BIN_DIR/zsh-tools"
  if [[ -L "$command_link" && "${command_link:A}" == "$ZT_ROOT/bin/zsh-tools" ]]; then
    command rm -- "$command_link"
  fi

  command rm -- "$ZT_CONFIG_DIR/init.zsh" "$ZT_CONFIG_DIR/enabled-modules.zsh" "$ZT_OWNER_FILE"
  command rmdir -- "$ZT_CONFIG_DIR" 2>/dev/null ||
    zt_warn "Preserved non-managed files in $ZT_CONFIG_DIR"

  print 'Uninstallation summary'
  zt_ok "Removed managed block from $ZT_ZSHRC"
  zt_ok "Removed $ZT_CONFIG_DIR"
  zt_ok 'Preserved repository and external dependencies'
  [[ -n "$backup" ]] && zt_ok "Created backup: $backup"
}

zt_status() {
  zt_read_enabled_modules
  if [[ ! -r "$ZT_OWNER_FILE" ]]; then
    zt_warn 'zsh-tools is not installed.'
    return 1
  fi

  local id missing command_name loaded ready=0 partial=0 failed=0
  print 'zsh-tools status'
  print
  for id in "${enabled_modules[@]}"; do
    loaded=true
    for command_name in ${=ZT_MODULE_COMMANDS[$id]}; do
      ZDOTDIR=/nonexistent zsh -dfc "source ${(q)ZT_CONFIG_DIR}/init.zsh; whence -w ${(q)command_name}" >/dev/null 2>&1 ||
        loaded=false
    done
    missing="$(zt_module_missing_dependencies "$id")"
    if [[ "$loaded" != true ]]; then
      zt_error "${ZT_MODULE_NAME[$id]}: failed"
      ((failed++))
    elif [[ -n "$missing" ]]; then
      zt_warn "${ZT_MODULE_NAME[$id]}: partial (missing: $missing)"
      ((partial++))
    else
      zt_ok "${ZT_MODULE_NAME[$id]}: ready"
      ((ready++))
    fi
  done
  print
  print "Modules: $ready ready / $partial partial / $failed failed"
  ((failed == 0))
}

zt_doctor() {
  local failures=0
  print 'zsh-tools doctor'
  print
  [[ -r "$ZT_OWNER_FILE" ]] && zt_ok 'Managed configuration found' ||
    { zt_error 'Managed configuration not found'; failures=1; }
  zt_validate_markers && zt_ok '.zshrc markers are consistent' ||
    { zt_error '.zshrc markers are inconsistent'; failures=1; }
  [[ -L "$ZT_BIN_DIR/zsh-tools" ]] && zt_ok 'Management command link found' ||
    { zt_error 'Management command link not found'; failures=1; }
  zt_status || failures=1
  return "$failures"
}

zt_set_module_state() {
  local action="$1" target="$2"
  zt_module_exists "$target" || { zt_error "Unknown module: $target"; return 2; }
  if [[ "$action" == enable ]] && ! zt_module_supported "$target"; then
    zt_error "Module '$target' does not support platform '$(zt_platform)'."
    return 2
  fi
  zt_read_enabled_modules
  local index="${enabled_modules[(Ie)$target]}"
  if [[ "$action" == enable ]]; then
    ((index)) || enabled_modules+=("$target")
  else
    ((index)) && enabled_modules[$index]=()
  fi
  zt_write_enabled_modules "${enabled_modules[@]}"
  zt_write_init
  zt_status
}

zt_list() {
  local id
  for id in "${ZT_MODULES[@]}"; do
    printf '%-14s %-18s %s\n' "$id" "${ZT_MODULE_NAME[$id]}" "${ZT_MODULE_DESCRIPTION[$id]}"
    print "  Commands: ${ZT_MODULE_COMMANDS[$id]}"
    print "  Dependencies: ${ZT_MODULE_DEPENDENCIES[$id]:-none}"
  done
}
