#!/usr/bin/env zsh

# Provide deterministic kubectl responses for tests.
emulate -L zsh
setopt ERR_EXIT NO_UNSET

case "$1 $2" in
  'api-resources --verbs=get,list')
    if [[ " $* " == *' --namespaced=true '* ]]; then
      print -l pods deployments configmaps secrets
    else
      print -l nodes namespaces storageclasses.storage.k8s.io
    fi
    ;;
  'get namespaces')
    print -l dev test
    ;;
  'get pods')
    if [[ " $* " == *' --field-selector=status.phase=Running '* ]]; then
      print -l pod-a pod-b
    else
      print 'NAME READY STATUS'
    fi
    ;;
  'get pod')
    print -l app sidecar
    ;;
  'get deployments')
    [[ "${MOCK_EMPTY_RESOURCE:-}" == deployments ]] || print -l api web
    ;;
  'get statefulsets')
    print database
    ;;
  'get services')
    print api
    ;;
  'get ingresses')
    print public
    ;;
  'get persistentvolumeclaims')
    print data
    ;;
  'get configmaps')
    print application
    ;;
  'get secrets')
    print credentials
    ;;
  'get nodes')
    print node-a
    ;;
  'describe '*|'exec '*)
    print -r -- "$*" >> "$MOCK_KUBECTL_LOG"
    ;;
  *)
    print -u2 -- "Unexpected kubectl arguments: $*"
    return 2
    ;;
esac
